### ISSUE TITLE
Group job ids are (now?) uuids

### ISSUE THREAD

**Issue by funnell** [Snakemake-Profiles/snakemake-lsf#19] opened 2020-04-11 23:26 UTC
Hello,

Group jobids seem to be string uuids which causes an error in lsf_submit.py
https://snakemake.readthedocs.io/en/stable/_modules/snakemake/jobs.html

**Comment by mbhall88** [comment] 2020-04-13 10:41
Could you please provide the error?

**Comment by leoisl** [comment] 2020-04-13 15:03
Just a reminder that grouped jobs is the only thing we are not testing currently in the job submitter, we should have tests covering it when closing this issue!

**Comment by funnell** [comment] 2020-04-13 20:03
Yes, sorry I don't remember the exact error. But the gist is that casting a part of the uuid string to int fails in this bit of code:
```
def jobid(self) -> int:
        if self.is_group_jobtype:
            return int(self.job_properties.get("jobid", "").split("-")[0])
        return int(self.job_properties.get("jobid"))
```

**Comment by mbhall88** [comment] 2020-04-14 08:15
Ok. I'll see if I can reproduce this and at the same time add some unit tests because as @leoisl says, this is about the only thing we aren't testing at the moment.

**Comment by mbhall88** [comment] 2020-04-14 10:52
I was able to reproduce this. An example error:

```
Traceback (most recent call last):                                                        │❯ xl
  File "/homes/mbhall88/.config/snakemake/lsf-dev/lsf_submit.py", line 237, in <module>   │Permissions Size User     Group Date Modified Name
    lsf_submit.submit()                                                                   │drwxrwxr-x     - mbhall88 iqbal  8 Apr 12:58  lsf
  File "/homes/mbhall88/.config/snakemake/lsf-dev/lsf_submit.py", line 206, in submit     │drwxrwxr-x     - mbhall88 iqbal 14 Apr 11:46  lsf-dev
    self._remove_previous_logs()  # we could be very unlucky of having the same 64-length │mbhall88 on noah-login-03 in ~/.config/snakemake at 11:46
random string with the same jobid                                                         │❯ cd lsf
  File "/homes/mbhall88/.config/snakemake/lsf-dev/lsf_submit.py", line 190, in _remove_pre│mbhall88 on noah-login-03 in ~/.config/snakemake/lsf via 🐍 pyenv 3.8.2 at 11:46
vious_logs                                                                                │❯ ..
    OSLayer.remove_file(self.outlog)                                                      │cmbhall88 on noah-login-03 in ~/.config/snakemake at 11:46
  File "/homes/mbhall88/.config/snakemake/lsf-dev/lsf_submit.py", line 142, in outlog     │❯ cd lsf-dev/
    jobid=self.jobid, random_string=self.random_string                                    │mbhall88 on noah-login-03 in ~/.config/snakemake/lsf-dev via 🐍 pyenv 3.8.2 at 11:46
  File "/homes/mbhall88/.config/snakemake/lsf-dev/lsf_submit.py", line 131, in jobid      │❯ xl
    return int(self.job_properties.get("jobid", "").split("-")[0])                        │Permissions Size User     Group Date Modified Name
ValueError: invalid literal for int() with base 10: '7b8d34a2'    
```

**Comment by mbhall88** [comment] 2020-04-14 11:03
As @funnell mentioned, it seems like snakemake are now using uuids for their group job IDs.

**Comment by mbhall88** [comment] 2020-04-14 14:31
Ok, #23 has a fix. Could either/both of you take a look and see if there are any problems with it before I merge?

**Closed** 2020-04-16 15:21 UTC
Labels: bug
